### ISSUE TITLE
Hynix P31 질문드립니다

### ISSUE THREAD

**Issue by amondnet** [dhckdgjs/GIGABYTE-Z590-VISION-G-HACKINTOSH-OPENCORE-iGPU-with-dGPU-UHD630-RX580#12]
안녕하세요

기존 시스템에 추가하려고 Hynix P31 1TB, 500GB 를 주문했습니다

1. gigabyte z390 + 8700k + RX 570 + samsung 970 Pro
2. gigabyte b550m + 5800x + gt 730 + samsung pm9a1

https://github.com/dortania/bugtracker/issues/192  
> Incompatible with IONVMeFamily (die under heavy load):
> SK Hynix P31

라고 나와 있어서 반품해야 하나 생각중이었습니다. 
혹시 Trim 이나 동작에는 이상이 없으신가요?

**Comment by dhckdgjs** [comment]
<img width="778" alt="Screen Shot 2021-07-14 at 6 12 37 AM" src="https://user-images.githubusercontent.com/35429874/125540053-203735a6-dc79-4c97-b721-2fb9f9494175.png">

### 속도 및 사용성
Blackmagic disk speed를 보시면 아시겠지만 속도는 큰 문제 없어 보입니다.
당연히 사용 상에도 별다른 이상을 발견한 적은 없는 것 같네요.

작은 크기의 파일이야 일상적 사용이라 평상시에도 문제를 못느꼈고,
제 경우에 30~200GB 사이의 단일 파일 이동이 잦음에도 큰 문제는 없는 것 같습니다.


<img width="936" alt="Screen Shot 2021-07-14 at 6 03 45 AM" src="https://user-images.githubusercontent.com/35429874/125540092-8569f5c0-d5cd-4637-9718-d4387092944c.png">

### Trim
일단 System info에서는 Trim support라고 나오긴 합니다만,
P31은 컨트롤러 자체적으로 Trim을 수행하는 것으로 알고 있기에 큰 의미는 없어 보입니다.

AHCI로 연결된 SATA SSD라면 Trim 활성화 여부가 중요할 수 있겠지만,
NVMe SSD인 P31의 경우 APFS의 Trim 명령이 통하지 않습니다.
100%라고 말하긴 약간 애매하지만 결론적으로 P31은 자체 컨트롤러가 Trim을 수행하기에
굳이 신경쓰지 않아도 될 것으로 예상합니다.


### 호환 여부
Dortania 깃에서 언제적 data를 기반으로 최종 업데이트 하였는지 모르겠지만,
일단 P31의 경우 tonymacx86 등 대부분의 관련 사이트에서 아직도 비호환으로 표기하고 있을겁니다.
이는 애초에 비호환으로 알려져 맥 유저들의 사용 시도 자체가 거의 없기에 업데이트가 늦는 것이지 않을까 합니다.

하지만 제가 readme에 기입한대로 Rev.41062C20(검정색 PCB) 제품이라면 즉시 사용이 가능하며,
기존 제품이라도 펌웨어 업데이트하면 동일하게 사용이 가능할 것으로 추정합니다.
(제가 가진 버전은 아니기에 100% 확신은 못하겠지만 일단은 가능해보입니다)


- 
PM981, 9A1 같은 제품들이 아니라면 사실 대부분 큰 문제는 없습니다.
애매하다면 하나만 개봉하셔서 써보시고 원하는 기능이 안된다면
그 때 970 Pro를 해킨으로 돌리시면 되지 않을까합니다 :)

**Comment by amondnet** [comment]
자세한 답변 감사합니다
