### ISSUE TITLE
Are you able to make and iGPU only working config?

### ISSUE THREAD

**Issue by picov** [dhckdgjs/GIGABYTE-Z590-VISION-G-HACKINTOSH-OPENCORE-iGPU-with-dGPU-UHD630-RX580#3]
I'm testing Asus ROG B560i with I5-10600 and get black screen just  before the OS installer.
I've tried to map frame buffer connectors with no luck.
Does your build works without the dGPU?

**Comment by dhckdgjs** [comment]
This efi works with dGPU+iGPU(headless).
If you have a AMD Navi, I recommend add agdpmod=pikera to boot args.
