### ISSUE TITLE
Ethernet

### ISSUE THREAD

**Issue by ejh4286** [dhckdgjs/GIGABYTE-Z590-VISION-G-HACKINTOSH-OPENCORE-iGPU-with-dGPU-UHD630-RX580#5]
Can you tell me what the manual hardware settings are? The Ethernet shows as connected in System Preferences-->Network, but will not connect to the internet.  Thank you.

**Comment by dhckdgjs** [comment]
Use 2.5g(or higher) switch hub/router.
If you use 1g or lower speed switch, you use this setting as below.
<img width="780" alt="D18F7154-D713-496C-A1CF-778C43B451E4" src="https://user-images.githubusercontent.com/35429874/118799462-b8a27280-b8d9-11eb-8413-171ccbd2958b.png">
