### ISSUE TITLE
Power Supply

### ISSUE THREAD

**Issue by ejh4286** [dhckdgjs/GIGABYTE-Z590-VISION-G-HACKINTOSH-OPENCORE-iGPU-with-dGPU-UHD630-RX580#6]
Did connect both the 4 pin and the 8 pin power connectors?

**Comment by dhckdgjs** [comment]
Nope. I use 8 pin connector only.

**Comment by ejh4286** [comment]
My system will run for about 8 to 10 minutes in windows or Mac and I get blue screen in windows and Mac just goes black.

**Comment by dhckdgjs** [comment]
Maybe that's the other problem beacuse both OS(Win & Mac) are NOT performing properly.

Some VGA cards have compatibility issues with this M/B like as below.


**Caution**
GIGABYTE Z590 Vision-G M/B(BIOS F2) CAN NOT BOOT with GIGABYTE RX580 MINING or GAMING. (Compatibility issue)

**Comment by ejh4286** [comment]
Thank you for the advice.  I removed the graphics card today and tried to run windows 10 on the integrated graphics.  Still very unstable and crashes within 10 - 15 minutes.  Then it won’t recognize any boot drives unless I power it down completely for about 15 minutes.  I think something on the board is over heating.  I’m returning it.
