### ISSUE TITLE
Big Sur 11.4

### ISSUE THREAD

**Issue by ejh4286** [dhckdgjs/GIGABYTE-Z590-VISION-G-HACKINTOSH-OPENCORE-iGPU-with-dGPU-UHD630-RX580#7]
Will you be releasing an EFI that us compatible with 11.4?  Thank you.

**Comment by dhckdgjs** [comment]
Unfortunately, I have not updated to a newer version of macOS because I use my gear for work. I'll post the most recent build information if I update in a few days.
By the way, is there anything problem in update procedure with my EFI?

**Comment by ejh4286** [comment]
> Unfortunately, I have not updated to a newer version of macOS because I use my gear for work. I'll post the most recent build information if I update in a few days.
> 
> By the way, is there anything problem in update procedure with my EFI?

11.4 freezes immediately after logging in.  There's been discussion on Tonymac that is associated with the 225 network controller on the board.  Several people describing the same behavior I have seen.

**Comment by dhckdgjs** [comment]
Oh, I heard similar issue related with nvme ssd. Freezing and stuttering.
I order nvme drive new one, if I find solution I’ll update thread few days later.

**Comment by dhckdgjs** [comment]
@ejh4286
Follow this link.
https://www.tonymacx86.com/threads/ohchangs-build-gigabyte-z590-vision-g-i7-10700k-amd-rx580.310986/post-2253791
