### ISSUE TITLE
USB ports stops working randomly sometimes

### ISSUE THREAD

**Issue by Nishant-Kathil** [dhckdgjs/GIGABYTE-Z590-VISION-G-HACKINTOSH-OPENCORE-iGPU-with-dGPU-UHD630-RX580#9]
Hi,

I have a Z590 Vision D board. Sometimes all my USB ports stops working and I need to reboot to get them working again.

thoughts?

**Comment by dhckdgjs** [comment]
> Hi,
> 
> I have a Z590 Vision D board. Sometimes all my USB ports stops working and I need to reboot to get them working again.
> 
> thoughts?


In fact, I can't figure out what's going on in your system with the information only you've provided.

Only USB ports stop working? 
Otherwise, will the entire system freeze or stutter? 

Check this guide if your entire system stops working.
(Delete/Disable vit9696 kernel patch)
https://www.tonymacx86.com/threads/ohchangs-build-gigabyte-z590-vision-g-i7-10700k-amd-rx580.310986/post-2253791

Then check this link also.
https://www.tonymacx86.com/threads/ohchangs-build-gigabyte-z590-vision-g-i7-10700k-amd-rx580.310986/post-2258474

**Comment by Nishant-Kathil** [comment]
> > Hi,
> > I have a Z590 Vision D board. Sometimes all my USB ports stops working and I need to reboot to get them working again.
> > thoughts?
> 
> In fact, I can't figure out what's going on in your system with the information only you've provided.
> 
> Only USB ports stop working?
> Otherwise, will the entire system freeze or stutter?
> 
> Check this guide if your entire system stops working.
> (Delete/Disable vit9696 kernel patch)
> https://www.tonymacx86.com/threads/ohchangs-build-gigabyte-z590-vision-g-i7-10700k-amd-rx580.310986/post-2253791
> 
> Then check this link also.
> https://www.tonymacx86.com/threads/ohchangs-build-gigabyte-z590-vision-g-i7-10700k-amd-rx580.310986/post-2258474

Sorry, for less information.

Only USB ports stop working? - **Yes**
Otherwise, will the entire system freeze or stutter? - **The entire system works fine and I can see activity on my screen (lets say if video is playing then it continues to work)**

I am using FakePCIID_Intel_I225-V.kext and other Kexts as per your latest OC release.

I have created my own USBMap.kext as I am using Vision D and the port mapping is different. Apart from this, rest of the things are used as is from your OC release. I am not using SSDT-UIAC-Z590-VISION-G-V3.aml from ACPI as I am using USBMap.kext

**Comment by dhckdgjs** [comment]
> > > Hi,
> > > I have a Z590 Vision D board. Sometimes all my USB ports stops working and I need to reboot to get them working again.
> > > thoughts?
> > 
> > 
> > In fact, I can't figure out what's going on in your system with the information only you've provided.
> > Only USB ports stop working?
> > Otherwise, will the entire system freeze or stutter?
> > Check this guide if your entire system stops working.
> > (Delete/Disable vit9696 kernel patch)
> > https://www.tonymacx86.com/threads/ohchangs-build-gigabyte-z590-vision-g-i7-10700k-amd-rx580.310986/post-2253791
> > Then check this link also.
> > https://www.tonymacx86.com/threads/ohchangs-build-gigabyte-z590-vision-g-i7-10700k-amd-rx580.310986/post-2258474
> 
> Sorry, for less information.
> 
> Only USB ports stop working? - **Yes**
> Otherwise, will the entire system freeze or stutter? - **The entire system works fine and I can see activity on my screen (lets say if video is playing then it continues to work)**
> 
> I am using FakePCIID_Intel_I225-V.kext and other Kexts as per your latest OC release.
> 
> I have created my own USBMap.kext as I am using Vision D and the port mapping is different. Apart from this, rest of the things are used as is from your OC release. I am not using SSDT-UIAC-Z590-VISION-G-V3.aml from ACPI as I am using USBMap.kext



First and foremost, I don't have Z590 Vision D Mainboard.
And I suppose Vision D is slightly different from Vision G. As a result, my EFI does not perfectly match your M/B.
I'm not confident that I'll be able to pinpoint the exact cause of your USB problem.

- In most cases, the best solution is to simply **rebuild USB map for 15 ports**(using Hackintool or something else)
A faulty USB port map can lead to a slew of issues.

- Add a SSDT for TB3. It's fine to create your own SSDT or to download someone else's.
If you need more info, check other threads as below.
https://github.com/SchmockLord/Gigabyte-Z590i-Vision-D-11900k
https://www.hackintosh-forum.de/forum/thread/53940-gigabyte-z590-vision-d-ethernet-aber-keine-netzwerkverbindung/
https://www.olarila.com/topic/14072-wip-step-by-step-z590-gigabyte-vision-d-i7-rocket-lake-s/
https://www.olarila.com/topic/14316-olarila-hackbeast-ga-z590-vision-d-with-thunderbolt-full-dsdt-patches-guide-and-discussion/


- **Remove the Fakepciid and Fakepciid_i225-v kext files**. Then follow the steps in this mini-guide. A new method for NIC connection loss.
https://www.tonymacx86.com/threads/ohchangs-build-gigabyte-z590-vision-g-i7-10700k-amd-rx580.310986/page-11#post-2258474
